# Generated by Django 3.2.4 on 2021-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(blank=True, max_length=200, null=True)),
                ('item2', models.CharField(blank=True, max_length=200, null=True)),
                ('item3', models.CharField(blank=True, max_length=200, null=True)),
                ('item4', models.CharField(blank=True, max_length=200, null=True)),
                ('item5', models.CharField(blank=True, max_length=200, null=True)),
                ('item6', models.CharField(blank=True, max_length=200, null=True)),
                ('item7', models.CharField(blank=True, max_length=200, null=True)),
                ('item8', models.CharField(blank=True, max_length=200, null=True)),
                ('item9', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Catégorie',
        ),
    ]
